import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

function parsePrice(priceStr: string): number {
  return parseInt(priceStr.replace(/[^\d]/g, ""), 10) * 100; // рубли → копейки
}

async function main() {
  const products = [
    {
      slug: "king-of-the-ring-tee",
      name: "Король Ринга",
      price: parsePrice("2 990 ₽"),
      category: "Верх",
      gender: "Мужчинам",
      collection: "ANGELvsDEMON",
      description: "Футболка «Король Ринга» — бокс",
      fullDescription: "Джеб, кросс, хук. Ангел уходит с линии. Демон врубает двойку.\n\nТы знаешь, как это — когда в голове отсчитывают не минуты, а раунды. Когда ангел в твоём углу шепчет: «Сними перчатки, у тебя уже есть нокаут». А демон бьёт в гонг: «Вставай, боец, десять секунд».\n\nЭта футболка про тот самый момент, когда ты решил не падать. Даже если канаты трясутся.\nТвой рекорд — не на бумаге. Он в крови.\n\nХлопок 220 г/м², оверсайз. Принт на спине.",
      details: JSON.stringify(["Оверсайз-крой с опущенным плечом", "Принт «Король Ринга» на спине (шелкография)", "Перед — чистый, без принта", "Плотность хлопка 220 г/м²", "Усиленные швы на плечах", "Ребристый воротник"]),
      material: "100% хлопок, 220 г/м²",
      care: "Машинная стирка при 30°C, вывернуть наизнанку, не сушить в сушилке, глажка при низкой температуре",
      sizes: JSON.stringify(["S", "M", "L", "XL"]),
      images: JSON.stringify(["/products/5314688838582086472.jpg", "/products/5314688838582086473.jpg"]),
      stock: 24,
      badge: "NEW",
      gradient: "from-[#0C0C0F] via-[#1a1510] to-[#C8C8D0]/10",
      pattern: "lines",
      icon: "tee",
      tag: "Бокс",
    },
    {
      slug: "death-press-tee",
      name: "Сила против воли",
      price: parsePrice("2 990 ₽"),
      category: "Верх",
      gender: "Мужчинам",
      collection: "ANGELvsDEMON",
      description: "Футболка «Сила против воли» — тяжёлая атлетика",
      fullDescription: "Демон жмёт лёжа. Ангел на подхвате. Но гриф не прощает слабаков.\n\nТы подходишь к штанге, когда пальцы ещё помнят прошлый вес. Ангел советует скинуть блины — безопасность важнее. Демон орёт: «Добавь пятак, трус!»\n\nВ этой футболке нет места для «потом». Есть только «сейчас». И демон всегда на твоей стороне, даже когда ты дрожишь. Потому что он знает: ты выжмешь эту чёртову штангу.\n\nХлопок 220 г/м², оверсайз. Принт на спине.",
      details: JSON.stringify(["Оверсайз-крой с опущенным плечом", "Принт «Смертельный Жим» на спине (шелкография)", "Перед — чистый, без принта", "Плотность хлопка 220 г/м²", "Усиленные швы на плечах"]),
      material: "100% хлопок, 220 г/м²",
      care: "Машинная стирка при 30°C, вывернуть наизнанку, не сушить в сушилке",
      sizes: JSON.stringify(["S", "M", "L", "XL"]),
      images: JSON.stringify(["/products/5314688838582086472.jpg", "/products/5314688838582086473.jpg"]),
      stock: 20,
      badge: "NEW",
      gradient: "from-[#0C0C0F] via-[#1a1210] to-[#C8C8D0]/10",
      pattern: "lines",
      icon: "tee",
      tag: "Жим штанги",
    },
    {
      slug: "holy-burn-tee",
      name: "В тисках",
      price: parsePrice("2 990 ₽"),
      category: "Верх",
      gender: "Мужчинам",
      collection: "ANGELvsDEMON",
      description: "Футболка «В тисках» — борьба",
      fullDescription: "Захват, который не отпускает. Ангел ищет слабину. Демон рвёт дистанцию.\n\nТы когда-нибудь чувствовал, как ковёр прожигает кожу? Как соперник вдавливает тебя в мат, а судья не слышит? Ангел советует туше — сдаться, выдохнуть. Демон скручивает шею: «Не смей. Борись, пока суставы не трещат».\n\nЭта футболка — для тех, кто знает: настоящая борьба начинается, когда сил уже нет. Победа не в баллах. Победа — когда ты не отпускаешь.\n\nХлопок 220 г/м², оверсайз. Принт на спине.",
      details: JSON.stringify(["Оверсайз-крой с опущенным плечом", "Принт «Священное Пламя» на спине (шелкография)", "Перед — чистый, без принта", "Плотность хлопка 220 г/м²", "Усиленные швы на плечах"]),
      material: "100% хлопок, 220 г/м²",
      care: "Машинная стирка при 30°C, вывернуть наизнанку, не сушить в сушилке",
      sizes: JSON.stringify(["S", "M", "L", "XL"]),
      images: JSON.stringify(["/products/5314688838582086472.jpg", "/products/5314688838582086473.jpg"]),
      stock: 22,
      badge: "NEW",
      gradient: "from-[#0C0C0F] via-[#1a1010] to-[#C8C8D0]/10",
      pattern: "lines",
      icon: "tee",
      tag: "Борьба",
    },
    {
      slug: "soul-lift-tee",
      name: "Исход схватки",
      price: parsePrice("2 990 ₽"),
      category: "Верх",
      gender: "Мужчинам",
      collection: "ANGELvsDEMON",
      description: "Футболка «Исход схватки» — армрестлинг",
      fullDescription: "Локоть на столе. Ладонь в ладони. Ангел моргает первым. Демон ломает запястье.\n\nЭто хитрее, чем кажется. Не бицепс решает, не спина. Решает тот, кто смотрит в глаза и не отводит взгляд. Ангел шепчет: «Опусти руку, ты уже устал». Демон вдавливает кулак в стол: «Дави, не смей отпускать».\n\nВ армрестлинге нет ничьих. Кто моргнул — тот проиграл. Кто отвёл руку — тот сдался. Эта футболка про финальную секунду, когда ты решаешь: «Я не уберу руку. Ни за что».\n\nОверсайз, хлопок 220 г/м², принт на спине.",
      details: JSON.stringify(["Оверсайз-крой с опущенным плечом", "Принт «Единый Подъём» на спине (шелкография)", "Перед — чистый, без принта", "Плотность хлопка 220 г/м²", "Усиленные швы на плечах"]),
      material: "100% хлопок, 220 г/м²",
      care: "Машинная стирка при 30°C, вывернуть наизнанку, не сушить в сушилке",
      sizes: JSON.stringify(["S", "M", "L", "XL"]),
      images: JSON.stringify(["/products/5314688838582086472.jpg", "/products/5314688838582086473.jpg"]),
      stock: 16,
      badge: "NEW",
      gradient: "from-[#0C0C0F] via-[#12100e] to-[#C8C8D0]/10",
      pattern: "lines",
      icon: "tee",
      tag: "Армрестлинг",
    },
    {
      slug: "concrete-shade-hoodie",
      name: "Concrete Shade Hoodie",
      price: parsePrice("8 990 ₽"),
      category: "Верх",
      gender: "Мужчинам",
      collection: "Борьба",
      description: "Плотный худи с kangaro-карманом и принтом «тень»",
      fullDescription: "Тяжёлое худи из хлопкового флиса с начёсом. Классический kangaro-карман, капюшон с регулировкой, принт «тень» на груди. Согревает даже в самый холодный рассвет.",
      details: JSON.stringify(["Плотный хлопковый флис с начёсом", "Kangaro-карман", "Регулируемый капюшон", "Принт на груди", "Эластичные манжеты"]),
      material: "80% хлопок, 20% полиэстер, 360 г/м²",
      care: "Машинная стирка 30°C, не отжимать",
      sizes: JSON.stringify(["S", "M", "L", "XL"]),
      stock: 10,
      badge: "HIT",
      gradient: "from-[#0C0C0F] via-[#1a1212] to-[#C8C8D0]/8",
      pattern: "cross",
      icon: "hoodie",
      tag: "Хит",
    },
    {
      slug: "shadow-track-pants",
      name: "Shadow Track Pants",
      price: parsePrice("5 990 ₽"),
      oldPrice: parsePrice("7 990 ₽"),
      category: "Низ",
      gender: "Мужчинам",
      collection: "Улица",
      description: "Сужающиеся трекшн-штаны с молниями на щиколотках",
      fullDescription: "Сужающиеся трекинг-штаны с застёжками-молниями на щиколотках. Эластичный пояс с кулиской, боковые карманы на молнии. Прямой силуэт, который переходит в сужающийся к низу.",
      details: JSON.stringify(["Сужающийся крой (tapered)", "Молнии на щиколотках", "Эластичный пояс с кулиской", "Боковые карманы на молнии"]),
      material: "65% хлопок, 35% полиэстер, 280 г/м²",
      care: "Машинная стирка 30°C",
      sizes: JSON.stringify(["S", "M", "L", "XL"]),
      stock: 8,
      badge: "SALE",
      gradient: "from-[#0C0C0F] via-[#161616] to-[#C8C8D0]/8",
      pattern: "lines",
      icon: "pants",
      tag: "Скидка",
    },
    {
      slug: "struggle-cap",
      name: "Struggle Cap",
      price: parsePrice("3 490 ₽"),
      category: "Аксессуары",
      gender: "Унисекс",
      collection: "Детали",
      description: "Бейсболка с тиснёным логотипом SOULDAWN",
      fullDescription: "Классическая шести-панельная бейсболка из жёсткого хлопка. Тиснёный логотип SOULDAWN на передней панели, регулируемая застёжка с металлической пряжкой. Сохраняет форму даже при активном движении.",
      details: JSON.stringify(["6 панелей, жёсткий каркас", "Тиснёный логотип", "Металлическая пряжка", "Впитывающая лента внутри"]),
      material: "100% хлопок",
      care: "Ручная стирка",
      sizes: JSON.stringify(["S/M", "L/XL"]),
      stock: 30,
      badge: "NEW",
      gradient: "from-[#0C0C0F] via-[#141210] to-[#C8C8D0]/6",
      pattern: "dots",
      icon: "cap",
      tag: "Новинка",
    },
    {
      slug: "steel-heart-tank",
      name: "Steel Heart Tank",
      price: parsePrice("3 990 ₽"),
      category: "Верх",
      gender: "Мужчинам",
      collection: "Борьба",
      description: "Рейта-топ из дышащего материала для тренировок",
      fullDescription: "Лёгкий танк-топ для интенсивных тренировок. Дышащий материал с технологией отведения влаги, свободный крой для максимальной подвижности. Минималистичная вышивка на груди.",
      details: JSON.stringify(["Дышащий материал с отведением влаги", "Свободный крой", "Усиленные швы", "Быстросохнущий"]),
      material: "92% полиэстер, 8% эластан",
      care: "Машинная стирка 30°C, не сушить в сушилке",
      sizes: JSON.stringify(["S", "M", "L", "XL"]),
      stock: 20,
      gradient: "from-[#0C0C0F] via-[#18140e] to-[#C8C8D0]/8",
      pattern: "dots",
      icon: "tee",
      tag: "",
    },
    {
      slug: "night-shift-joggers",
      name: "Night Shift Joggers",
      price: parsePrice("6 990 ₽"),
      category: "Низ",
      gender: "Мужчинам",
      collection: "Улица",
      description: "Утеплённые джоггеры с карманами-молниями",
      fullDescription: "Утеплённые джоггеры из плотного трикотажа с флисовой подкладкой. Карманы на молнии, эластичные манжеты, регулировка пояса. Идеальны для холодных утренних пробежек и уличных прогулок.",
      details: JSON.stringify(["Флисовая подкладка", "Карманы на молнии", "Эластичные манжеты", "Регулируемый пояс", "Рефлексивные элементы"]),
      material: "80% хлопок, 20% полиэстер, 320 г/м²",
      care: "Машинная стирка 30°C",
      sizes: JSON.stringify(["S", "M", "L", "XL"]),
      stock: 12,
      badge: "HIT",
      gradient: "from-[#0C0C0F] via-[#1a1010] to-[#C8C8D0]/8",
      pattern: "cross",
      icon: "pants",
      tag: "Хит",
    },
    {
      slug: "dawnbreak-bomber",
      name: "Dawnbreak Bomber",
      price: parsePrice("14 990 ₽"),
      category: "Верх",
      gender: "Мужчинам",
      collection: "Борьба",
      description: "Бомбер с атласной подкладкой и нашивкой на рукаве",
      fullDescription: "Премиальный бомбер с атласной подкладкой и наполнителем из синтепона. Водоотталкивающая внешняя ткань, нашивка на рукаве, эластичные манжеты и подол. Легендарный силуэт для легендарных людей.",
      details: JSON.stringify(["Атласная подкладка", "Водоотталкивающая ткань", "Нашивка на рукаве", "Эластичные манжеты и подол", "Два боковых кармана на молнии"]),
      material: "100% нейлон, подкладка — полиэстер",
      care: "Машинная стирка 30°C, не отжимать",
      sizes: JSON.stringify(["S", "M", "L", "XL"]),
      stock: 6,
      badge: "NEW",
      gradient: "from-[#0C0C0F] via-[#1e1610] to-[#C8C8D0]/10",
      pattern: "lines",
      icon: "bomber",
      tag: "Новинка",
    },
    {
      slug: "urban-grip-socks",
      name: "Urban Grip Socks",
      price: parsePrice("1 790 ₽"),
      category: "Аксессуары",
      gender: "Унисекс",
      collection: "Детали",
      description: "Компрессионные носки с anti-slip подошвой",
      fullDescription: "Компрессионные носки с анатомическим плетением и anti-slip подошвой. Поддерживают свод стопы, снижают усталость при длительных нагрузках.",
      details: JSON.stringify(["Компрессионное плетение", "Anti-slip подошва", "Анатомическая поддержка свода", "Антибактериальная пропитка"]),
      material: "75% хлопок, 15% полиамид, 10% эластан",
      care: "Машинная стирка 40°C",
      sizes: JSON.stringify(["38-40", "41-43", "44-46"]),
      stock: 50,
      gradient: "from-[#0C0C0F] via-[#121212] to-[#C8C8D0]/8",
      pattern: "none",
      icon: "socks",
      tag: "",
    },
    {
      slug: "battle-crossbody",
      name: "Battle Crossbody",
      price: parsePrice("5 490 ₽"),
      category: "Аксессуары",
      gender: "Унисекс",
      collection: "Детали",
      description: "Кросс-бэг из водонепроницаемого нейлона",
      fullDescription: "Компактный кросс-бэг из водонепроницаемого нейлона 500D. Регулируемая лямка, внутренние карманы-органайзер, скрытая карманка на молнии. Идеальный размер для телефона, ключей и кошелька.",
      details: JSON.stringify(["Водонепроницаемый нейлон 500D", "Регулируемая лямка", "Внутренний органайзер", "Скрытый карман на молнии"]),
      material: "100% нейлон 500D",
      care: "Протирать влажной тканью",
      sizes: JSON.stringify(["Универсальный"]),
      stock: 15,
      badge: "NEW",
      gradient: "from-[#0C0C0F] via-[#14120e] to-[#C8C8D0]/6",
      pattern: "dots",
      icon: "bag",
      tag: "Новинка",
    },
    {
      slug: "iron-grip-wraps",
      name: "Iron Grip Wraps",
      price: parsePrice("2 190 ₽"),
      category: "Аксессуары",
      gender: "Унисекс",
      collection: "Детали",
      description: "Бинты для кистей из хлопка с липучкой",
      fullDescription: "Профессиональные бинты для кистей из плотного хлопка. Липучка для надёжной фиксации, эластичный материал для идеального обхвата.",
      details: JSON.stringify(["Плотный хлопок", "Липучка для фиксации", "Эластичный материал", "Длина 120 см"]),
      material: "100% хлопок",
      care: "Ручная стирка",
      sizes: JSON.stringify(["S/M", "L/XL"]),
      stock: 40,
      gradient: "from-[#0C0C0F] via-[#181414] to-[#C8C8D0]/8",
      pattern: "none",
      icon: "wraps",
      tag: "",
    },
    {
      slug: "void-long-sleeve",
      name: "Void Long Sleeve",
      price: parsePrice("5 990 ₽"),
      category: "Верх",
      gender: "Мужчинам",
      collection: "Борьба",
      description: "Длинный рукав из тонкого джерси, лёгкий слой",
      fullDescription: "Тонкий лонгслив из мягкого джерси для межсезонья. Прямой крой, рёбра на манжетах и подоле, вышивка на рукаве.",
      details: JSON.stringify(["Тонкий джерси", "Рёбра на манжетах и подоле", "Вышивка на рукаве", "Прямой крой"]),
      material: "95% хлопок, 5% эластан, 180 г/м²",
      care: "Машинная стирка 30°C",
      sizes: JSON.stringify(["S", "M", "L", "XL"]),
      stock: 18,
      gradient: "from-[#0C0C0F] via-[#14100e] to-[#C8C8D0]/6",
      pattern: "cross",
      icon: "longsleeve",
      tag: "",
    },
    {
      slug: "grit-cargo-pants",
      name: "Grit Cargo Pants",
      price: parsePrice("8 490 ₽"),
      category: "Низ",
      gender: "Мужчинам",
      collection: "Улица",
      description: "Карго с 6 карманами и регулируемой штаниной",
      fullDescription: "Многофункциональные карго-штаны с 6 карманами, включая объёмные боковые на липучке. Регулируемая штанина с застёжками-кнопками, усиленные колени.",
      details: JSON.stringify(["6 карманов, включая 2 объёмных", "Регулируемая штанина", "Усиленные колени", "Застёжки-кнопки", "Эластичный пояс"]),
      material: "65% хлопок, 35% полиэстер, 300 г/м²",
      care: "Машинная стирка 30°C",
      sizes: JSON.stringify(["S", "M", "L", "XL"]),
      stock: 9,
      badge: "NEW",
      gradient: "from-[#0C0C0F] via-[#161410] to-[#C8C8D0]/8",
      pattern: "lines",
      icon: "cargo",
      tag: "Новинка",
    },
  ];

  console.log(`Seeding ${products.length} products...`);
  for (const p of products) {
    const result = await prisma.product.upsert({
      where: { slug: p.slug },
      create: p,
      update: p,
    });
    console.log(`  ✓ ${result.name}`);
  }
  console.log("Done!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
