"""SOULDAWN — Database package. Re-export everything."""
from database.connection import (
    init_db,
    dispose_db,
    set_bot,
    get_or_create_user,
    get_user_cart,
    save_user_cart,
    save_order,
    get_user_orders,
    get_all_users,
    get_stats,
    get_full_stats,
    update_user_heartbeat,
    get_online_users,
    get_recent_orders,
    get_paid_unnotified_orders,
    mark_order_processing,
    add_expense,
    get_expenses,
    delete_expense,
    update_user_notifications,
    log_action,
    create_ticket,
    get_ticket,
    get_ticket_by_message_id,
    get_ticket_by_accepted_admin,
    take_ticket,
    update_ticket_admin_messages,
    get_open_tickets,
    close_ticket,
    update_ticket_status,
    deactivate_user,
)

__all__ = [
    "init_db", "dispose_db", "set_bot",
    "get_or_create_user", "get_user_cart", "save_user_cart",
    "save_order", "get_user_orders", "get_all_users",
    "get_stats", "get_full_stats",
    "update_user_heartbeat", "get_online_users", "get_recent_orders",
    "get_paid_unnotified_orders", "mark_order_processing",
    "add_expense", "get_expenses", "delete_expense",
    "update_user_notifications", "log_action",
    "create_ticket", "get_ticket", "get_ticket_by_message_id",
    "get_ticket_by_accepted_admin",
    "take_ticket", "update_ticket_admin_messages", "get_open_tickets",
    "close_ticket", "update_ticket_status",
    "deactivate_user",
]
